# this file is meant for Docker Swarm stacks only
# trying it in compose will fail because of multiple replicas trying to bind to the same port
# Swarm currently does not support Compose Spec, so we'll pin to the older version 3.9

version: "3.9"

services:
  api:
    image: jomardev25/nodejs-api:1.0.0
    ports:
      - 8080:8080
    networks:
      - nodjs-api-network
    deploy:
      restart_policy:
        condition: on-failure # none, on-failure, any
        delay: 5s # How long to wait between restart attempts
        max_attempts: 3 # How many times to attempt to restart a container before giving up (default: never give up)
        window: 120s # How long to wait before deciding if a restart has succeeded
      replicas: 2 #  Number of containers to be run
      resources:
        limits:
          # service is constrained to use no more than 50M of memory and 0.50 (50% of a single core) of available processing time (CPU)
          cpus: '0.50'
          memory: 50M
        reservations:
          # service has 20M of memory and 0.25 CPU time reserved (as always available to it)
          cpus: '0.25'
          memory: 20M
    environment:
      - UPLOAD_PATH=/uploads

networks:
  nodjs-api-network: