---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-api
  namespace: default
spec:
  strategy:
    type: Recreate
  replicas: 4
  selector:
    matchLabels:
      app: nodejs-api
  template:
    metadata:
      labels:
        app: nodejs-api
    spec:
      containers:
        - name: nodejs-api
          image: jomardev25/nodejs-api:2.0.0
          env:
            - name: UPLOAD_PATH
              value: /uploads
          ports:
            - name: http
              containerPort: 8080
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5