apiVersion: v1
kind: Service
metadata:
  name: nodejs-api
  namespace: default
spec:
  selector:
    app: nodejs-api
    replica: blue
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http