server:
  port: 8080

spring:
  application:
    name: GleamPost
  datasource:
    url: jdbc:postgresql://localhost:5432/gleam_post
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      enabled: "true"
      max-request-size: 500KB
      file-size-threshold: 2KB
      max-file-size: 500KB

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: trace

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  file:
    upload-root-dir: ./public/uploads
    upload-dir: 
      articles: ./public/uploads
      profiles: ./public/uploads/profiles
