server:
  port: 8080

spring:
  application:
    name: GleamPost
  datasource:
    url: 'jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}'
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: "true"
  jackson:
    property-naming-strategy: SNAKE_CASE
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      enabled: "true"
      max-request-size: 215MB
      file-size-threshold: 2KB
      max-file-size: 200MB
  flyway:
    baseline-on-migrate: "true"
    enabled: "false"
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    baseline-description: "init"
    baseline-version: 0

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: trace

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  file:
    upload-root-dir: ${UPLOAD_PATH}
    base-url: http://localhost:8080
    upload-dir: 
      articles: ./public/uploads
      profiles: ./public/uploads/profiles
