version: '3.8'

services:
  app:
    build:
      context: ""
      dockerfile: Dockerfile
    container_name: app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www
    networks:
      - php-dev-networks
    depends_on:
      - db
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    restart: always
    ports:
      - "9090:80"
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - php-dev-networks
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:8.0
    volumes:
      - ./storage/mysql:/var/lib/mysql
      - ./db/init.sql:/data/application/init.sql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=docker_demo
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - php-dev-networks
    command: --init-file /data/application/init.sql
networks:
  php-dev-networks:
    external: true