apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nodejs-api
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: nodejs-api
  template:
    metadata:
      labels:
        tier: nodejs-api
    spec:
      containers:
        - name: nodejs-api
          image: jomardev25/nodejs-api:1.0.0
